apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../keycloak-operator/deploy/

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: RELATED_IMAGE_KEYCLOAK
          value: "dankirkpatrick/keycloak:latest"
    target:
      kind: Deployment
      namespace: keycloak
      name: keycloak-operator

images:
  - name: quay.io/keycloak/keycloak-operator
    newTag: 17.0.0
